import { CampaignType, DiscountType, PaymentMethod, TableStatus } from "@prisma/client";
import type { PosSettingsResource } from "./pos-settings.resources";

export interface PosSettingsFieldOption {
  label: string;
  value: string;
  meta?: Record<string, unknown>;
}

export interface PosSettingsFieldConfig {
  key: string;
  label: string;
  type: "text" | "number" | "textarea" | "switch" | "select" | "datetime" | "json";
  required?: boolean;
  placeholder?: string;
  options?: PosSettingsFieldOption[];
  optionSource?: "branches" | "categories" | "tableAreas" | "customers" | "vatRates" | "inventoryItems";
  section?: string;
  helperText?: string;
  fullWidth?: boolean;
}

export interface PosSettingsColumnConfig {
  key: string;
  label: string;
}

export interface PosSettingsFilterConfig {
  key: string;
  label: string;
  type: "text" | "select" | "boolean";
  options?: PosSettingsFieldOption[];
}

export interface PosSettingsResourceConfig {
  key: PosSettingsResource;
  title: string;
  description: string;
  delegate: string;
  branchScoped: boolean;
  include?: Record<string, unknown>;
  staticWhere?: Record<string, unknown>;
  searchFields: string[];
  orderBy: Record<string, "asc" | "desc">;
  fields: PosSettingsFieldConfig[];
  columns: PosSettingsColumnConfig[];
  filters: PosSettingsFilterConfig[];
  numberFields?: string[];
  booleanFields?: string[];
  jsonFields?: string[];
  dateFields?: string[];
  enumFields?: Record<string, string[]>;
  relationOptionKeys?: Array<"branches" | "categories" | "tableAreas" | "customers" | "vatRates" | "inventoryItems">;
}

const discountOptions = Object.values(DiscountType).map((value) => ({ label: value, value }));
const paymentMethodOptions = Object.values(PaymentMethod).map((value) => ({ label: value, value }));
const tableStatusOptions = Object.values(TableStatus).map((value) => ({ label: value, value }));

const menuProductConfig: PosSettingsResourceConfig = {
  key: "menu-management",
  title: "Menu Yonetimi",
  description: "Urun, kategori baglantisi ve varyant girisleri",
  delegate: "menuProduct",
  branchScoped: false,
  include: {
    category: { include: { defaultVatRate: true } },
    branch: true,
    vatRate: true,
    recipe: {
      include: {
        items: {
          include: {
            inventoryItem: {
              include: {
                unit: true,
                stockEntries: {
                  where: { unitCost: { not: null } },
                  orderBy: { createdAt: "desc" },
                  take: 1,
                },
              },
            },
          },
        },
      },
    },
    unitCosts: { orderBy: { effectiveAt: "desc" }, take: 1 },
    variants: true,
  },
  searchFields: ["name", "slug", "sku"],
  orderBy: { updatedAt: "desc" },
  relationOptionKeys: ["branches", "categories", "vatRates", "inventoryItems"],
  fields: [
    { key: "branchId", label: "Sube", type: "select", optionSource: "branches", section: "Temel Bilgiler" },
    { key: "categoryId", label: "Kategori", type: "select", optionSource: "categories", required: true, section: "Temel Bilgiler" },
    { key: "name", label: "Urun Adi", type: "text", required: true, placeholder: "Orn. Ice Latte", section: "Temel Bilgiler" },
    { key: "slug", label: "Slug", type: "text", required: true, placeholder: "ice-latte", section: "Temel Bilgiler" },
    { key: "sku", label: "SKU", type: "text", section: "Temel Bilgiler" },
    { key: "imageUrl", label: "Urun Gorseli URL", type: "text", placeholder: "https://...", section: "Temel Bilgiler", fullWidth: true },
    { key: "description", label: "Aciklama", type: "textarea", section: "Temel Bilgiler", fullWidth: true },
    { key: "basePrice", label: "Satis Fiyati", type: "number", required: true, section: "Fiyat ve KDV" },
    { key: "currentCost", label: "Birim Maliyet", type: "number", helperText: "Kaydedildiginde yeni bir UnitCost kaydi olusturulur.", section: "Fiyat ve KDV" },
    { key: "isVatAuto", label: "Oto KDV Ayarla", type: "switch", helperText: "Kategori varsayilan KDV'si secilebilir, istersen elle degistirebilirsin.", section: "Fiyat ve KDV" },
    { key: "vatRateId", label: "KDV Orani", type: "select", optionSource: "vatRates", section: "Fiyat ve KDV" },
    { key: "isActive", label: "Aktif", type: "switch", section: "Gorunurluk ve Kanal" },
    { key: "isVisible", label: "POS'ta Goster", type: "switch", helperText: "Kapaliysa urun satis ekraninda cikmaz, eski kayitlar korunur.", section: "Gorunurluk ve Kanal" },
    { key: "showInQr", label: "QR Menu'de Goster", type: "switch", section: "Gorunurluk ve Kanal" },
    { key: "stockTracked", label: "Stok Takipli", type: "switch", section: "Stok ve Recete" },
    { key: "stockItemId", label: "Stok Kalemi", type: "select", optionSource: "inventoryItems", section: "Stok ve Recete" },
    { key: "recipeEnabled", label: "Recete Baglantisi", type: "switch", helperText: "Aktif oldugunda satis tamamlandiginda recetedeki hammaddeler otomatik duser.", section: "Stok ve Recete" },
    {
      key: "recipeItemsJson",
      label: "Recete Satirlari",
      type: "json",
      optionSource: "inventoryItems",
      helperText: "Her satirda hammadde ve miktar secilir. Birim, secilen hammadde kartindan otomatik gelir.",
      placeholder: "[{\"inventoryItemId\":\"...\",\"quantity\":18}]",
      section: "Stok ve Recete",
      fullWidth: true,
    },
    { key: "calories", label: "Kalori", type: "number", section: "Ek Bilgiler" },
    { key: "allergenInfo", label: "Alerjen Bilgisi", type: "textarea", section: "Ek Bilgiler", fullWidth: true },
    { key: "variantsJson", label: "Varyant JSON", type: "json", placeholder: "[{\"name\":\"Buyuk\",\"priceDiff\":10}]", section: "Ek Bilgiler", fullWidth: true },
  ],
  columns: [
    { key: "name", label: "Urun" },
    { key: "category.name", label: "Kategori" },
    { key: "branch.name", label: "Sube" },
    { key: "basePrice", label: "Fiyat" },
    { key: "currentCost", label: "Maliyet" },
    { key: "theoreticalCost", label: "Recete Maliyeti" },
    { key: "vatRateLabel", label: "KDV" },
    { key: "visibilityLabel", label: "POS" },
    { key: "showInQr", label: "QR" },
    { key: "isActive", label: "Aktif" },
    { key: "stockTrackingLabel", label: "Stok" },
    { key: "recipeStatus", label: "Recete" },
  ],
  filters: [
    { key: "search", label: "Ara", type: "text" },
    { key: "branchId", label: "Sube", type: "select" },
    { key: "categoryId", label: "Kategori", type: "select" },
    { key: "vatRateId", label: "KDV", type: "select" },
    {
      key: "isVisible",
      label: "POS Durumu",
      type: "select",
      options: [
        { label: "Tum Kayıtlar", value: "" },
        { label: "POS'ta Gorunenler", value: "true" },
        { label: "POS'tan Cikarilanlar", value: "false" },
      ],
    },
    {
      key: "showInQr",
      label: "QR Durumu",
      type: "select",
      options: [
        { label: "Tum Kayıtlar", value: "" },
        { label: "QR'da Gorunenler", value: "true" },
        { label: "QR'da Gizlenenler", value: "false" },
      ],
    },
    {
      key: "isActive",
      label: "Aktiflik",
      type: "select",
      options: [
        { label: "Tum Kayıtlar", value: "" },
        { label: "Aktif", value: "true" },
        { label: "Pasif", value: "false" },
      ],
    },
    {
      key: "stockTracking",
      label: "Stok Takibi",
      type: "select",
      options: [
        { label: "Tum Kayıtlar", value: "" },
        { label: "Takipli", value: "tracked" },
        { label: "Takipsiz", value: "untracked" },
      ],
    },
  ],
  numberFields: ["basePrice", "currentCost", "calories"],
  booleanFields: ["isVisible", "showInQr", "isVatAuto", "isActive", "stockTracked", "recipeEnabled"],
  jsonFields: ["variantsJson", "recipeItemsJson"],
};

export const posSettingsRegistry: Record<PosSettingsResource, PosSettingsResourceConfig> = {
  "menu-management": menuProductConfig,
  "menu-products": {
    ...menuProductConfig,
    key: "menu-products",
    title: "Urunler",
    description: "Menu urunleri ve fiyatlari",
  },
  "menu-categories": {
    key: "menu-categories",
    title: "Kategoriler",
    description: "Menu kategori yonetimi",
    delegate: "menuCategory",
    branchScoped: false,
    include: {
      branch: true,
      parent: true,
      defaultVatRate: true,
    },
    searchFields: ["name", "slug"],
    orderBy: { sortOrder: "asc" },
    relationOptionKeys: ["branches", "categories", "vatRates"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", optionSource: "branches", section: "Temel Bilgiler" },
      { key: "name", label: "Kategori Adi", type: "text", required: true, section: "Temel Bilgiler" },
      { key: "slug", label: "Slug", type: "text", required: true, section: "Temel Bilgiler" },
      { key: "parentId", label: "Ust Kategori", type: "select", optionSource: "categories", section: "Temel Bilgiler" },
      { key: "defaultVatRateId", label: "Varsayilan KDV", type: "select", optionSource: "vatRates", section: "Temel Bilgiler" },
      {
        key: "printerType",
        label: "Yazici Tipi",
        type: "select",
        section: "Yazici",
        options: [
          { label: "Mutfak", value: "kitchen" },
          { label: "Bar", value: "bar" },
        ],
      },
      { key: "sortOrder", label: "Sira", type: "number", section: "Gorunurluk" },
      { key: "isVisible", label: "POS'ta Goster", type: "switch", section: "Gorunurluk" },
      { key: "showInQr", label: "QR Menu'de Goster", type: "switch", section: "Gorunurluk" },
    ],
    columns: [
      { key: "name", label: "Kategori" },
      { key: "parent.name", label: "Ust Kategori" },
      { key: "branch.name", label: "Sube" },
      { key: "defaultVatRate.name", label: "KDV" },
      { key: "printerType", label: "Yazici" },
      { key: "sortOrder", label: "Sira" },
      { key: "isVisible", label: "POS" },
      { key: "showInQr", label: "QR" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
      {
        key: "isVisible",
        label: "POS Durumu",
        type: "select",
        options: [
          { label: "Tum Kayitlar", value: "" },
          { label: "POS'ta Gorunenler", value: "true" },
          { label: "POS'tan Cikarilanlar", value: "false" },
        ],
      },
      {
        key: "showInQr",
        label: "QR Durumu",
        type: "select",
        options: [
          { label: "Tum Kayitlar", value: "" },
          { label: "QR'da Gorunenler", value: "true" },
          { label: "QR'da Gizlenenler", value: "false" },
        ],
      },
    ],
    numberFields: ["sortOrder"],
    booleanFields: ["isVisible", "showInQr"],
  },
  campaigns: {
    key: "campaigns",
    title: "Kampanyalar",
    description: "Tum kampanya kurallari",
    delegate: "campaign",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["name"],
    orderBy: { startsAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Kampanya", type: "text", required: true },
      { key: "type", label: "Tip", type: "select", required: true, options: Object.values(CampaignType).map((value) => ({ label: value, value })) },
      { key: "discountType", label: "Indirim Tipi", type: "select", required: true, options: discountOptions },
      { key: "priority", label: "Oncelik", type: "number" },
      { key: "isAutomatic", label: "Otomatik", type: "switch" },
      { key: "startsAt", label: "Baslangic", type: "datetime", required: true },
      { key: "endsAt", label: "Bitis", type: "datetime" },
      { key: "conditionsJson", label: "Kosullar JSON", type: "json" },
      { key: "benefitsJson", label: "Faydalar JSON", type: "json" },
    ],
    columns: [
      { key: "name", label: "Kampanya" },
      { key: "branch.name", label: "Sube" },
      { key: "type", label: "Tip" },
      { key: "discountType", label: "Indirim" },
      { key: "startsAt", label: "Baslangic" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["priority"],
    booleanFields: ["isAutomatic"],
    jsonFields: ["conditionsJson", "benefitsJson"],
    dateFields: ["startsAt", "endsAt"],
    enumFields: {
      type: Object.values(CampaignType),
      discountType: Object.values(DiscountType),
    },
  },
  "happy-hour": {
    key: "happy-hour",
    title: "Happy Hour",
    description: "Saat bazli kampanya yonetimi",
    delegate: "campaign",
    branchScoped: true,
    include: { branch: true },
    staticWhere: { type: CampaignType.HAPPY_HOUR },
    searchFields: ["name"],
    orderBy: { startsAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Kural Adi", type: "text", required: true },
      { key: "discountType", label: "Indirim Tipi", type: "select", required: true, options: discountOptions },
      { key: "priority", label: "Oncelik", type: "number" },
      { key: "startsAt", label: "Baslangic", type: "datetime", required: true },
      { key: "endsAt", label: "Bitis", type: "datetime" },
      { key: "conditionsJson", label: "Saat Kural JSON", type: "json" },
      { key: "benefitsJson", label: "Indirim JSON", type: "json" },
    ],
    columns: [
      { key: "name", label: "Happy Hour" },
      { key: "branch.name", label: "Sube" },
      { key: "discountType", label: "Indirim" },
      { key: "startsAt", label: "Baslangic" },
      { key: "endsAt", label: "Bitis" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["priority"],
    jsonFields: ["conditionsJson", "benefitsJson"],
    dateFields: ["startsAt", "endsAt"],
    enumFields: {
      discountType: Object.values(DiscountType),
    },
  },
  "timed-discounts": {
    key: "timed-discounts",
    title: "Sureli Indirimler",
    description: "Tarih ve saat bazli indirimler",
    delegate: "campaign",
    branchScoped: true,
    include: { branch: true },
    staticWhere: { type: CampaignType.TIMED },
    searchFields: ["name"],
    orderBy: { startsAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Indirim Adi", type: "text", required: true },
      { key: "discountType", label: "Indirim Tipi", type: "select", required: true, options: discountOptions },
      { key: "priority", label: "Oncelik", type: "number" },
      { key: "startsAt", label: "Baslangic", type: "datetime", required: true },
      { key: "endsAt", label: "Bitis", type: "datetime", required: true },
      { key: "conditionsJson", label: "Kosullar JSON", type: "json" },
      { key: "benefitsJson", label: "Indirim JSON", type: "json" },
    ],
    columns: [
      { key: "name", label: "Indirim" },
      { key: "branch.name", label: "Sube" },
      { key: "discountType", label: "Tip" },
      { key: "startsAt", label: "Baslangic" },
      { key: "endsAt", label: "Bitis" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["priority"],
    jsonFields: ["conditionsJson", "benefitsJson"],
    dateFields: ["startsAt", "endsAt"],
    enumFields: {
      discountType: Object.values(DiscountType),
    },
  },
  "qr-menu": {
    key: "qr-menu",
    title: "QR Menu",
    description: "QR yayin, tema ve karsilama ayarlari",
    delegate: "qrMenuSetting",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["themeName", "welcomeTitle"],
    orderBy: { updatedAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "themeName", label: "Tema", type: "text", required: true },
      { key: "accentColor", label: "Accent Renk", type: "text" },
      { key: "logoAssetUrl", label: "Logo URL", type: "text" },
      { key: "coverImageUrl", label: "Kapak URL", type: "text" },
      { key: "welcomeTitle", label: "Baslik", type: "text" },
      { key: "welcomeText", label: "Aciklama", type: "textarea" },
      { key: "isPublished", label: "Yayinda", type: "switch" },
    ],
    columns: [
      { key: "branch.name", label: "Sube" },
      { key: "themeName", label: "Tema" },
      { key: "accentColor", label: "Accent" },
      { key: "isPublished", label: "Yayin" },
    ],
    filters: [{ key: "branchId", label: "Sube", type: "select" }],
    booleanFields: ["isPublished"],
  },
  "table-sections": {
    key: "table-sections",
    title: "Bolumler / Masalar",
    description: "Masa ve alan tanimlari",
    delegate: "diningTable",
    branchScoped: true,
    include: { branch: true, area: true },
    searchFields: ["name", "code"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["branches", "tableAreas"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "areaId", label: "Bolum", type: "select" },
      { key: "code", label: "Kod", type: "text", required: true },
      { key: "name", label: "Masa Adi", type: "text", required: true },
      { key: "colorHex", label: "Renk", type: "text" },
      { key: "capacity", label: "Kapasite", type: "number" },
      { key: "status", label: "Durum", type: "select", options: tableStatusOptions },
    ],
    columns: [
      { key: "name", label: "Masa" },
      { key: "branch.name", label: "Sube" },
      { key: "area.name", label: "Bolum" },
      { key: "capacity", label: "Kapasite" },
      { key: "status", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["capacity"],
    enumFields: {
      status: Object.values(TableStatus),
    },
  },
  "delivery-addresses": {
    key: "delivery-addresses",
    title: "Paket Servis Adresleri",
    description: "Musteri teslimat adresleri",
    delegate: "customerAddress",
    branchScoped: false,
    include: { customer: true },
    searchFields: ["title", "addressLine", "district", "city"],
    orderBy: { title: "asc" },
    relationOptionKeys: ["customers"],
    fields: [
      { key: "customerId", label: "Musteri", type: "select", required: true },
      { key: "title", label: "Adres Basligi", type: "text", required: true },
      { key: "city", label: "Sehir", type: "text" },
      { key: "district", label: "Ilce", type: "text" },
      { key: "addressLine", label: "Acik Adres", type: "textarea", required: true },
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
      { key: "isDefault", label: "Varsayilan", type: "switch" },
    ],
    columns: [
      { key: "title", label: "Baslik" },
      { key: "customer.fullName", label: "Musteri" },
      { key: "city", label: "Sehir" },
      { key: "district", label: "Ilce" },
      { key: "isDefault", label: "Varsayilan" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["latitude", "longitude"],
    booleanFields: ["isDefault"],
  },
  customers: {
    key: "customers",
    title: "Musteriler",
    description: "Musteri kartlari",
    delegate: "customer",
    branchScoped: false,
    include: { branch: true, addresses: true },
    searchFields: ["fullName", "phone", "email"],
    orderBy: { updatedAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "fullName", label: "Musteri Adi", type: "text", required: true },
      { key: "phone", label: "Telefon", type: "text" },
      { key: "email", label: "E-posta", type: "text" },
      { key: "birthDate", label: "Dogum Tarihi", type: "datetime" },
      { key: "notes", label: "Not", type: "textarea" },
    ],
    columns: [
      { key: "fullName", label: "Musteri" },
      { key: "phone", label: "Telefon" },
      { key: "email", label: "E-posta" },
      { key: "branch.name", label: "Sube" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    dateFields: ["birthDate"],
  },
  "optional-products": {
    key: "optional-products",
    title: "Opsiyonel Urunler",
    description: "Modifier grup ve opsiyonlari",
    delegate: "modifierGroup",
    branchScoped: false,
    include: { options: true },
    searchFields: ["name"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["inventoryItems"],
    fields: [
      { key: "name", label: "Grup Adi", type: "text", required: true },
      { key: "selectionMin", label: "Min Secim", type: "number" },
      { key: "selectionMax", label: "Max Secim", type: "number" },
      {
        key: "optionsJson",
        label: "Opsiyon JSON",
        type: "json",
        placeholder: "[{\"name\":\"Extra Shot\",\"priceDiff\":20,\"inventoryItemId\":\"...\",\"stockQuantity\":1}]",
      },
    ],
    columns: [
      { key: "name", label: "Grup" },
      { key: "selectionMin", label: "Min" },
      { key: "selectionMax", label: "Max" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["selectionMin", "selectionMax"],
    jsonFields: ["optionsJson"],
  },
  "required-choice-groups": {
    key: "required-choice-groups",
    title: "Zorunlu Secim Gruplari",
    description: "Secimi zorunlu grup yapilari",
    delegate: "requiredChoiceGroup",
    branchScoped: false,
    include: { options: true },
    searchFields: ["name"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["inventoryItems"],
    fields: [
      { key: "name", label: "Grup Adi", type: "text", required: true },
      { key: "selectionMin", label: "Min Secim", type: "number" },
      { key: "selectionMax", label: "Max Secim", type: "number" },
      {
        key: "optionsJson",
        label: "Secim JSON",
        type: "json",
        placeholder: "[{\"name\":\"Ek Peynir\",\"priceDiff\":15,\"inventoryItemId\":\"...\",\"stockQuantity\":1}]",
      },
    ],
    columns: [
      { key: "name", label: "Grup" },
      { key: "selectionMin", label: "Min" },
      { key: "selectionMax", label: "Max" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["selectionMin", "selectionMax"],
    jsonFields: ["optionsJson"],
  },
  "payment-methods": {
    key: "payment-methods",
    title: "Odeme Yontemleri",
    description: "Sube ve tenant bazli odeme configleri",
    delegate: "paymentMethodConfig",
    branchScoped: false,
    include: { branch: true },
    searchFields: ["name", "code", "providerKey"],
    orderBy: { sortOrder: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "name", label: "Ad", type: "text", required: true },
      { key: "code", label: "Kod", type: "text", required: true },
      { key: "providerKey", label: "Provider Key", type: "text" },
      { key: "paymentMethod", label: "Payment Enum", type: "select", required: true, options: paymentMethodOptions },
      { key: "feeRate", label: "Komisyon %", type: "number" },
      { key: "sortOrder", label: "Sira", type: "number" },
      { key: "isActive", label: "Aktif", type: "switch" },
      { key: "settingsJson", label: "Ayar JSON", type: "json" },
    ],
    columns: [
      { key: "name", label: "Yontem" },
      { key: "code", label: "Kod" },
      { key: "paymentMethod", label: "Enum" },
      { key: "branch.name", label: "Sube" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["feeRate", "sortOrder"],
    booleanFields: ["isActive"],
    jsonFields: ["settingsJson"],
    enumFields: {
      paymentMethod: Object.values(PaymentMethod),
    },
  },
  "defined-devices": {
    key: "defined-devices",
    title: "Tanimli Cihazlar",
    description: "POS cihaz envanteri",
    delegate: "posDevice",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["name", "code", "deviceType", "platform"],
    orderBy: { updatedAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Cihaz Adi", type: "text", required: true },
      { key: "code", label: "Kod", type: "text", required: true },
      { key: "deviceType", label: "Tip", type: "text", required: true },
      { key: "platform", label: "Platform", type: "text" },
      { key: "ipAddress", label: "IP", type: "text" },
      { key: "status", label: "Durum", type: "text" },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "name", label: "Cihaz" },
      { key: "code", label: "Kod" },
      { key: "deviceType", label: "Tip" },
      { key: "branch.name", label: "Sube" },
      { key: "status", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    booleanFields: ["isActive"],
  },
  terminals: {
    key: "terminals",
    title: "Terminaller",
    description: "Terminal heartbeat ve tanimlari",
    delegate: "terminal",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["name", "code", "ipAddress", "status"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Terminal", type: "text", required: true },
      { key: "code", label: "Kod", type: "text", required: true },
      { key: "ipAddress", label: "IP", type: "text" },
      { key: "status", label: "Durum", type: "text" },
      { key: "heartbeatAt", label: "Heartbeat", type: "datetime" },
    ],
    columns: [
      { key: "name", label: "Terminal" },
      { key: "code", label: "Kod" },
      { key: "branch.name", label: "Sube" },
      { key: "status", label: "Durum" },
      { key: "heartbeatAt", label: "Heartbeat" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    dateFields: ["heartbeatAt"],
  },
  printers: {
    key: "printers",
    title: "Yazicilar",
    description: "Fis entegrasyonlari ve fiziksel yazici tanimlari",
    delegate: "printer",
    branchScoped: true,
    include: { branch: true, printDestination: true },
    searchFields: ["name", "displayName", "type", "connectionUri"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true, section: "Temel" },
      { key: "displayName", label: "Fis Adi", type: "text", required: true, placeholder: "Orn. Mutfak Fisi", section: "Temel" },
      { key: "name", label: "Yazici Adi (Windows)", type: "text", required: true, placeholder: "EPSON TM-T88VI Receipt", section: "Temel" },
      { key: "printDestinationId", label: "Fislik", type: "select", section: "Temel", helperText: "Bu yazicinin bagli oldugu fislik/station." },
      { key: "type", label: "Tip", type: "text", required: true, section: "Baglanti" },
      {
        key: "connectionUri",
        label: "Baglanti",
        type: "text",
        required: true,
        placeholder: "bridge://local",
        helperText: "Local bridge icin bridge://local, ag yazici icin tcp://IP:9100",
        section: "Baglanti",
      },
      { key: "isKitchen", label: "Mutfak (legacy)", type: "switch", section: "Baglanti" },
      { key: "isActive", label: "Aktif", type: "switch", section: "Durum" },
    ],
    columns: [
      { key: "displayName", label: "Fis Adi" },
      { key: "name", label: "Yazici Adi" },
      { key: "printDestination.code", label: "Fislik" },
      { key: "branch.name", label: "Sube" },
      { key: "connectionUri", label: "Baglanti" },
      { key: "isActive", label: "Aktif" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    booleanFields: ["isKitchen", "isActive"],
  },
  "back-screen-slider": {
    key: "back-screen-slider",
    title: "Arka Ekran Slider",
    description: "POS arka ekran slide yonetimi",
    delegate: "backScreenSlide",
    branchScoped: false,
    include: { branch: true },
    searchFields: ["title", "subtitle", "mediaUrl"],
    orderBy: { sortOrder: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "title", label: "Baslik", type: "text", required: true },
      { key: "subtitle", label: "Alt Baslik", type: "textarea" },
      { key: "mediaUrl", label: "Gorsel URL", type: "text", required: true },
      { key: "ctaLabel", label: "CTA", type: "text" },
      { key: "ctaUrl", label: "CTA URL", type: "text" },
      { key: "sortOrder", label: "Sira", type: "number" },
      { key: "isActive", label: "Aktif", type: "switch" },
      { key: "startsAt", label: "Baslangic", type: "datetime" },
      { key: "endsAt", label: "Bitis", type: "datetime" },
    ],
    columns: [
      { key: "title", label: "Slide" },
      { key: "branch.name", label: "Sube" },
      { key: "sortOrder", label: "Sira" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["sortOrder"],
    booleanFields: ["isActive"],
    dateFields: ["startsAt", "endsAt"],
  },
  "table-colors": {
    key: "table-colors",
    title: "Masa Renkleri",
    description: "Masa durum renk kurallari",
    delegate: "tableColorRule",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["name", "colorHex", "textColorHex"],
    orderBy: { createdAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "name", label: "Renk Adi", type: "text", required: true },
      { key: "tableStatus", label: "Masa Durumu", type: "select", required: true, options: tableStatusOptions },
      { key: "colorHex", label: "Arka Plan", type: "text", required: true },
      { key: "textColorHex", label: "Yazi Rengi", type: "text" },
      { key: "isDefault", label: "Varsayilan", type: "switch" },
    ],
    columns: [
      { key: "name", label: "Ad" },
      { key: "tableStatus", label: "Durum" },
      { key: "colorHex", label: "Renk" },
      { key: "branch.name", label: "Sube" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    booleanFields: ["isDefault"],
    enumFields: {
      tableStatus: Object.values(TableStatus),
    },
  },
  "discount-types": {
    key: "discount-types",
    title: "Indirim Turleri",
    description: "Yonetilebilir indirim setleri",
    delegate: "discountTypeConfig",
    branchScoped: false,
    include: { branch: true },
    searchFields: ["name", "code"],
    orderBy: { updatedAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "name", label: "Ad", type: "text", required: true },
      { key: "code", label: "Kod", type: "text", required: true },
      { key: "discountType", label: "Tip", type: "select", required: true, options: discountOptions },
      { key: "defaultValue", label: "Varsayilan Tutar", type: "number" },
      { key: "approvalRequired", label: "Onay Gerekli", type: "switch" },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "name", label: "Indirim" },
      { key: "code", label: "Kod" },
      { key: "discountType", label: "Tip" },
      { key: "branch.name", label: "Sube" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["defaultValue"],
    booleanFields: ["approvalRequired", "isActive"],
    enumFields: {
      discountType: Object.values(DiscountType),
    },
  },
  "preset-notes": {
    key: "preset-notes",
    title: "On Tanimli Notlar",
    description: "Hizli servis notlari",
    delegate: "presetNote",
    branchScoped: false,
    include: { branch: true },
    searchFields: ["title", "content", "noteType"],
    orderBy: { sortOrder: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "title", label: "Baslik", type: "text", required: true },
      { key: "content", label: "Icerik", type: "textarea", required: true },
      { key: "noteType", label: "Tur", type: "text" },
      { key: "sortOrder", label: "Sira", type: "number" },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "title", label: "Baslik" },
      { key: "noteType", label: "Tur" },
      { key: "branch.name", label: "Sube" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["sortOrder"],
    booleanFields: ["isActive"],
  },
  settings: {
    key: "settings",
    title: "Ayarlar",
    description: "Merkezi POS config kayitlari",
    delegate: "posSetting",
    branchScoped: false,
    include: { branch: true },
    searchFields: ["key", "description"],
    orderBy: { updatedAt: "desc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select" },
      { key: "key", label: "Anahtar", type: "text", required: true },
      { key: "description", label: "Aciklama", type: "textarea" },
      { key: "valueJson", label: "Deger JSON", type: "json", required: true },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "key", label: "Key" },
      { key: "branch.name", label: "Sube" },
      { key: "description", label: "Aciklama" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    booleanFields: ["isActive"],
    jsonFields: ["valueJson"],
  },
};
