export const moduleManifest = [
  { key: "auth", basePath: "/auth", scope: "public" },
  { key: "companies", basePath: "/companies", scope: "tenant" },
  { key: "branches", basePath: "/branches", scope: "tenant" },
  { key: "iam", basePath: "/iam", scope: "tenant" },
  { key: "pos-settings", basePath: "/pos-settings", scope: "tenant" },
  { key: "dashboard", basePath: "/dashboard", scope: "branch" },
  { key: "pos", basePath: "/pos", scope: "branch" },
  { key: "menu", basePath: "/menu", scope: "branch" },
  { key: "campaigns", basePath: "/campaigns", scope: "branch" },
  { key: "tables", basePath: "/tables", scope: "branch" },
  { key: "customers", basePath: "/customers", scope: "branch" },
  { key: "staff", basePath: "/staff", scope: "branch" },
  { key: "attendance", basePath: "/attendance", scope: "branch" },
  { key: "accounting", basePath: "/accounting", scope: "tenant" },
  { key: "inventory", basePath: "/inventory", scope: "branch" },
  { key: "reports", basePath: "/reports", scope: "tenant" },
  { key: "integrations", basePath: "/integrations", scope: "tenant" },
  { key: "subscriptions", basePath: "/subscriptions", scope: "tenant" },
  { key: "audit", basePath: "/audit", scope: "tenant" },
  { key: "notifications", basePath: "/notifications", scope: "user" },
  { key: "support", basePath: "/support", scope: "tenant" },
];
