export const posCapabilities = {
  channels: ["table", "self_service", "delivery", "takeaway", "qr_order"],
  actions: [
    "product.add",
    "product.remove",
    "product.variant.select",
    "product.required_choice.select",
    "product.optional_modifier.select",
    "ticket.note.add",
    "ticket.note.preset.apply",
    "ticket.rename",
    "ticket.customer.assign",
    "ticket.cover.update",
    "discount.apply",
    "discount.line.apply",
    "campaign.apply",
    "ticket.merge",
    "ticket.split",
    "ticket.transfer",
    "ticket.hold",
    "ticket.resume",
    "ticket.void",
    "ticket.refund",
    "drawer.open",
    "label.print",
    "kitchen.print",
    "receipt.print",
    "payment.collect",
    "payment.partial.collect",
    "payment.change.calculate",
    "approval.request",
  ],
  payments: ["cash", "credit_card", "meal_card", "coupon", "on_account", "other"],
  realtime: [
    "table.status.changed",
    "ticket.updated",
    "payment.completed",
    "ticket.locked",
    "pending-order.created",
    "approval.required",
    "kitchen.status.changed",
  ],
  offlineStrategy: "mutation-queue-with-replay",
  stateLayers: ["sessionStore", "catalogStore", "tablesStore", "ticketStore", "paymentStore", "syncStore"],
  criticalApprovalActions: ["ticket.void", "ticket.refund", "drawer.open", "discount.line.apply", "ticket.merge"],
} as const;

export const posScreenArchitecture = {
  topBar: ["modeSwitcher", "globalSearch", "sessionInfo", "quickActions", "pendingOrders", "orderHistory"],
  catalogArea: ["categoryTabs", "subcategoryTabs", "productGrid", "virtualKeyboard", "speedFilters"],
  rightPanel: ["ticketHeader", "customerCard", "lineItems", "totals", "quickActionDock", "paymentCTA"],
  drawers: ["variantDrawer", "modifierDrawer", "noteDrawer", "discountDrawer", "approvalDrawer", "paymentDrawer"],
} as const;

export const posPerformanceRules = [
  "memoized-derived-totals",
  "chunked-product-rendering",
  "lazy-mounted-drawers",
  "optimistic-ticket-mutations",
  "queued-offline-replay",
  "non-blocking-printer-jobs",
] as const;
