import type { SidebarItem } from "@adisyon/types";

export type AdminSidebarItem = SidebarItem & {
  allPermissions?: string[];
  anyPermissions?: string[];
  children?: AdminSidebarItem[];
};

export const adminSidebar: AdminSidebarItem[] = [
  { key: "dashboard", label: "Anasayfa", href: "/", icon: "layout-dashboard", description: "Operasyon merkezi", enabled: true, anyPermissions: ["dashboard.view"] },
  {
    key: "organization",
    label: "Isletme",
    href: "/isletme",
    icon: "building-2",
    description: "Tenant ve sube yonetimi",
    enabled: true,
    anyPermissions: ["dashboard.view", "staff.manage", "subscription.manage"],
    defaultOpen: true,
    children: [
      { key: "company", label: "Isletme Bilgileri", href: "/isletme", enabled: true, anyPermissions: ["subscription.manage"] },
      { key: "branches", label: "Subeler", href: "/subeler", enabled: true, anyPermissions: ["dashboard.view", "staff.manage"] },
    ],
  },
  {
    key: "revenue",
    label: "Ciro",
    href: "/ciro",
    icon: "wallet",
    description: "Gelir akisi ve trend analizi",
    enabled: true,
    anyPermissions: ["ciro.view", "reports.view"],
    defaultOpen: true,
    children: [
      { key: "revenue-overview", label: "Genel Ciro", href: "/ciro", enabled: true, anyPermissions: ["ciro.view", "reports.view"] },
      { key: "revenue-by-branch", label: "Sube Bazli Ciro", href: "/ciro/sube-bazli", enabled: true, anyPermissions: ["ciro.view", "reports.view"] },
    ],
  },
  {
    key: "pos-settings",
    label: "POS Ayarlari",
    href: "/pos-ayarlari",
    icon: "settings-2",
    enabled: true,
    anyPermissions: ["pos_settings.view", "product.manage", "payment_method.view", "device.view"],
    defaultOpen: true,
    children: [
      { key: "menu-products", label: "Urunler", href: "/pos-ayarlari/urunler", description: "Menu urunleri ve fiyatlar", enabled: true, anyPermissions: ["product.manage", "pos_settings.view"] },
      { key: "menu-categories", label: "Kategoriler", href: "/pos-ayarlari/kategoriler", description: "Menu kategori listesi", enabled: true, anyPermissions: ["product.manage", "pos_settings.view"] },
      { key: "campaigns", label: "Kampanyalar", href: "/pos-ayarlari/kampanyalar", description: "Sepet ve urun kampanyalari", enabled: true },
      { key: "happy-hour", label: "Happy Hour", href: "/pos-ayarlari/happy-hour", description: "Saat bazli fiyatlama", enabled: true },
      { key: "timed-discounts", label: "Sureli Indirimler", href: "/pos-ayarlari/sureli-indirimler", description: "Tarih ve saat planli indirimler", enabled: true },
      { key: "qr-menu", label: "QR Menu", href: "/pos-ayarlari/qr-menu", description: "Dijital menu yayin akisi", enabled: true },
      { key: "sections-tables", label: "Bolumler / Masalar", href: "/pos-ayarlari/masalar", description: "Salon plani ve masa durumu", enabled: true },
      { key: "delivery-addresses", label: "Paket Servis Adresleri", href: "/pos-ayarlari/paket-servis-adresleri", description: "Teslimat bolgeleri ve adresler", enabled: true },
      { key: "customers", label: "Musteriler", href: "/pos-ayarlari/musteriler", description: "Musteri havuzu ve segmentler", enabled: true },
      { key: "optional-products", label: "Opsiyonel Urunler", href: "/pos-ayarlari/opsiyonel-urunler", description: "Modifier ve ek urunler", enabled: true },
      { key: "required-groups", label: "Zorunlu Secim Gruplari", href: "/pos-ayarlari/zorunlu-secim-gruplari", description: "Secim zorunlu urun akislari", enabled: true },
      { key: "payments", label: "Odeme Yontemleri", href: "/pos-ayarlari/odeme-yontemleri", description: "Odeme tipi ve entegrasyonlar", enabled: true, anyPermissions: ["payment_method.view", "payment_method.manage"] },
      { key: "devices", label: "Tanimli Cihazlar", href: "/pos-ayarlari/tanimli-cihazlar", description: "Kiosk, tablet, terminal envanteri", enabled: true, anyPermissions: ["device.view", "device.manage"] },
      { key: "terminals", label: "Terminaller", href: "/pos-ayarlari/terminaller", description: "Terminal performansi ve heartbeat", enabled: true, anyPermissions: ["device.view", "device.manage"] },
      { key: "printers", label: "Yazicilar", href: "/pos-ayarlari/yazicilar", description: "Mutfak ve fis yazici yonetimi", enabled: true, anyPermissions: ["device.view", "device.manage"] },
      { key: "print-integrations", label: "Fis Entegrasyonlari", href: "/pos-ayarlari/fis-entegrasyonlari", description: "Fislik routing, yazici testi ve baglanti", enabled: true, anyPermissions: ["device.view", "device.manage"] },
      { key: "slider", label: "Arka Ekran Slider", href: "/pos-ayarlari/arka-ekran-slider", description: "POS arka ekran kreatifleri", enabled: true },
      { key: "table-colors", label: "Masa Renkleri", href: "/pos-ayarlari/masa-renkleri", description: "Durum bazli renk sistemleri", enabled: true },
      { key: "discount-types", label: "Indirim Turleri", href: "/pos-ayarlari/indirim-turleri", description: "Yuzde ve tutar bazli setler", enabled: true },
      { key: "notes", label: "On Tanimli Notlar", href: "/pos-ayarlari/on-tanimli-notlar", description: "Hizli servis notlari", enabled: true },
      { key: "settings", label: "Ayarlar", href: "/pos-ayarlari/ayarlar", description: "Genel POS davranis ayarlari", enabled: true },
      { key: "system-backups", label: "Yedekleme", href: "/pos-ayarlari/yedekleme", description: "Backup, restore ve loglar", enabled: true, anyPermissions: ["subscription.manage"] },
      { key: "feature-flags", label: "Feature Flags", href: "/pos-ayarlari/feature-flags", description: "Ozellikleri kontrollu ac/kapat", enabled: true, anyPermissions: ["feature_flags.view", "feature_flags.manage"] },
    ],
  },
  {
    key: "staff",
    label: "Personel Yonetimi",
    href: "/personel",
    icon: "users",
    enabled: true,
    anyPermissions: ["staff.view", "staff.manage", "attendance.view", "attendance.manage"],
    children: [
      { key: "staff-team", label: "Yonetici & Personel", href: "/personel/yonetici-ve-personel", enabled: true },
      { key: "staff-goals", label: "Hedefler", href: "/personel/hedefler", enabled: true },
      { key: "staff-tasks", label: "Gorev & To-Do", href: "/personel/gorev-ve-todo", enabled: true },
      { key: "staff-notifications", label: "Personel Bildirimleri", href: "/personel/personel-bildirimleri", enabled: true },
      { key: "staff-payroll", label: "Maas Yonetimi", href: "/personel/maas-yonetimi", enabled: true },
      { key: "staff-shifts", label: "Mesai Yonetimi", href: "/personel/mesai-yonetimi", enabled: true },
      { key: "staff-breaks", label: "Mola Sureleri", href: "/personel/mola-sureleri", enabled: true },
      { key: "staff-tracking", label: "Personel Takip", href: "/personel/personel-takip", enabled: true },
      { key: "staff-roles", label: "Personel Rolleri", href: "/personel/personel-rolleri", enabled: true },
      { key: "staff-discounts", label: "Personel Indirimleri", href: "/personel/personel-indirimleri", enabled: true },
      { key: "waiter-logs", label: "Garson Loglari", href: "/personel/garson-loglari", enabled: true, anyPermissions: ["reports.view", "staff.view"] },
      { key: "staff-audit-questions", label: "Operasyon Devamli Sorular", href: "/personel/operasyon-devamli-sorular", enabled: true },
      { key: "staff-audit-survey", label: "Operasyon Devamli Anketi", href: "/personel/operasyon-devamli-anketi", enabled: true },
    ],
  },
  { key: "attendance-qr", label: "Mesai / Mola QR", href: "/mesai-qr", icon: "qr-code", description: "QR tabanli mesai ve mola akisi", enabled: true, anyPermissions: ["attendance.view", "attendance.manage"] },
  { key: "monitoring", label: "Monitoring", href: "/monitoring", icon: "activity", description: "API hata analizi ve alert takibi", enabled: true, anyPermissions: ["monitoring.view"] },
  {
    key: "accounting",
    label: "Muhasebe Kayitlari",
    href: "/muhasebe",
    icon: "receipt-text",
    enabled: true,
    anyPermissions: ["accounting.view", "reports.view"],
    children: [
      { key: "accounts", label: "Hesaplar", href: "/muhasebe/hesaplar", enabled: true },
      { key: "tickets", label: "Adisyon Listesi", href: "/muhasebe/adisyon-listesi", enabled: true },
      { key: "sold-products", label: "Satilan Urunler", href: "/muhasebe/satilan-urunler", enabled: true },
      { key: "payments", label: "Odemeler", href: "/muhasebe/odemeler", enabled: true },
      { key: "vat-rates", label: "Urun KDV Oranlari", href: "/muhasebe/urun-kdv-oranlari", enabled: true },
      { key: "suppliers", label: "Tedarikciler", href: "/muhasebe/tedarikciler", enabled: true },
      { key: "supplier-vat", label: "Tedarikci KDV Raporlari", href: "/muhasebe/tedarikci-kdv-raporlari", enabled: true },
      { key: "business-customers", label: "Musteri Isletmeler", href: "/muhasebe/musteri-isletmeler", enabled: true },
      { key: "customer-vat", label: "Musteri KDV Raporlari", href: "/muhasebe/musteri-kdv-raporlari", enabled: true },
      { key: "invoices", label: "Faturalar", href: "/muhasebe/faturalar", enabled: true },
      { key: "invoice-items", label: "Fatura Kalemleri", href: "/muhasebe/fatura-kalemleri", enabled: true },
      { key: "unit-costs", label: "Birim Maliyetler", href: "/muhasebe/birim-maliyetler", enabled: true },
      { key: "cash-closures", label: "Kasa Kapanislari", href: "/muhasebe/kasa-kapanislari", enabled: true },
      { key: "fixed-costs", label: "Sabit Maliyetler", href: "/muhasebe/sabit-maliyetler", enabled: true },
      { key: "payroll", label: "Personel Odemeleri", href: "/muhasebe/personel-odemeleri", enabled: true },
      { key: "other-payments", label: "Diger Odemeler", href: "/muhasebe/diger-odemeler", enabled: true },
    ],
  },
  {
    key: "inventory",
    label: "Stok",
    href: "/stok",
    icon: "package",
    enabled: true,
    anyPermissions: ["inventory.view", "inventory.manage"],
    children: [
      { key: "warehouses", label: "Depolar", href: "/stok/depolar", enabled: true },
      { key: "transfers", label: "Depo Transfer", href: "/stok/depo-transfer", enabled: true },
      { key: "units", label: "Stok Birimleri", href: "/stok/stok-birimleri", enabled: true },
      { key: "inventory-categories", label: "Stoklu Urun Kategorileri", href: "/stok/stoklu-urun-kategorileri", enabled: true },
      { key: "inventory-products", label: "Stoklu Urunler", href: "/stok/stoklu-urunler", enabled: true },
      { key: "stock-entry", label: "Stok Girisi", href: "/stok/stok-girisi", enabled: true },
      { key: "stock-status", label: "Stok Durumu", href: "/stok/stok-durumu", enabled: true },
      { key: "stock-cards", label: "Stok Kartlari", href: "/stok/stok-kartlari", enabled: true },
      { key: "waste-products", label: "Atik Urunler", href: "/stok/atik-urunler", enabled: true },
    ],
  },
  {
    key: "reports",
    label: "Raporlar",
    href: "/raporlar",
    icon: "bar-chart-3",
    enabled: true,
    anyPermissions: ["reports.view", "ciro.view"],
    children: [
      { key: "sales-reports", label: "Satis Raporlari", href: "/raporlar/satis-raporlari", enabled: true },
      { key: "payment-method-reports", label: "Odeme Tipi Raporlari", href: "/raporlar/odeme-tipi-raporlari", enabled: true },
      { key: "expense-reports", label: "Gider Raporlari", href: "/raporlar/gider-raporlari", enabled: true },
      { key: "cash-closure-reports", label: "Kasa Kapanis Raporlari", href: "/raporlar/kasa-kapanis-raporlari", enabled: true },
      { key: "discount-reports", label: "Indirim Raporlari", href: "/raporlar/indirim-raporlari", enabled: true },
      { key: "category-revenue", label: "Kategori Cirosu", href: "/raporlar/kategori-ciro", enabled: true },
      { key: "product-reports", label: "Urun Raporlari", href: "/raporlar/urun-raporlari", enabled: true },
      { key: "profitability-reports", label: "Maliyet & Karlilik", href: "/raporlar/maliyet-karlilik-raporlari", enabled: true },
      { key: "stock-reports", label: "Stok Raporlari", href: "/raporlar/stok-raporlari", enabled: true },
      { key: "consumption-reports", label: "Hammadde Tuketim", href: "/raporlar/hammadde-tuketim-raporlari", enabled: true },
      { key: "finance-reports", label: "Finans Raporlari", href: "/raporlar/finans-raporlari", enabled: true },
      { key: "employee-reports", label: "Calisan Raporlari", href: "/raporlar/calisan-raporlari", enabled: true },
      { key: "shift-reports", label: "Mesai Raporlari", href: "/raporlar/mesai-raporlari", enabled: true },
      { key: "goal-bonus-reports", label: "Hedef & Prim Raporlari", href: "/raporlar/hedef-ve-prim-raporlari", enabled: true },
      { key: "cancel-list", label: "Iptal Listesi", href: "/raporlar/iptal-listesi", enabled: true, anyPermissions: ["reports.view"] },
    ],
  },
  {
    key: "integrations",
    label: "Entegrasyonlar",
    href: "/entegrasyonlar",
    icon: "plug",
    enabled: true,
    anyPermissions: ["integrations.view", "device.view"],
    children: [{ key: "pos-devices", label: "POS Cihazlari", href: "/entegrasyonlar/pos-cihazlari", enabled: true, anyPermissions: ["integrations.view", "device.view"] }],
  },
  { key: "staff-discounts-shortcut", label: "Personel İndirimleri", href: "/personel/personel-indirimleri", icon: "badge-percent", description: "Yetkili indirim ve limitler", enabled: true, anyPermissions: ["staff.view", "staff.manage"] },
  { key: "audit", label: "Audit Log", href: "/audit", icon: "shield-check", description: "Sistem iz kayitlari", enabled: true, anyPermissions: ["reports.view"] },
  { key: "subscription", label: "Abonelik", href: "/abonelik", icon: "credit-card", description: "Plan, limit ve kullanim", enabled: true, anyPermissions: ["subscription.view", "subscription.manage"] },
  { key: "support", label: "Destek", href: "/destek", icon: "life-buoy", description: "Destek talepleri", enabled: true, anyPermissions: ["support.view", "support.manage"] },
  { key: "product-ratings", label: "Urun Puanlari", href: "/urun-puanlari", icon: "star", description: "Musteri urun geri bildirimleri", enabled: true, anyPermissions: ["reports.view", "product.manage"] },
  { key: "go-pos", label: "Satış Ekranına Git", href: "/satis-ekranina-git", icon: "monitor-up", description: "Canlı satış operasyonuna geç", enabled: true },
];
