export interface RouteItem {
  module: string;
  title: string;
  path: string;
  listView: boolean;
  detailView: boolean;
  createFlow: boolean;
  exportable: boolean;
}

export const adminRouteManifest: RouteItem[] = [
  { module: "dashboard", title: "Anasayfa", path: "/", listView: false, detailView: false, createFlow: false, exportable: true },
  { module: "ciro", title: "Ciro", path: "/ciro", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "ciro-by-branch", title: "Sube Bazli Ciro", path: "/ciro/sube-bazli", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "menu", title: "Menu Yonetimi", path: "/pos-ayarlari/menu", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "campaigns", title: "Kampanyalar", path: "/pos-ayarlari/kampanyalar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "happy-hour", title: "Happy Hour", path: "/pos-ayarlari/happy-hour", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "timed-discounts", title: "Sureli Indirimler", path: "/pos-ayarlari/sureli-indirimler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "qr-menu", title: "QR Menu", path: "/pos-ayarlari/qr-menu", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "tables", title: "Bolumler / Masalar", path: "/pos-ayarlari/masalar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "delivery-addresses", title: "Paket Servis Adresleri", path: "/pos-ayarlari/paket-servis-adresleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "customers", title: "Musteriler", path: "/pos-ayarlari/musteriler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "optional-products", title: "Opsiyonel Urunler", path: "/pos-ayarlari/opsiyonel-urunler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "required-choice-groups", title: "Zorunlu Secim Gruplari", path: "/pos-ayarlari/zorunlu-secim-gruplari", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "payment-methods", title: "Odeme Yontemleri", path: "/pos-ayarlari/odeme-yontemleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "devices", title: "Tanimli Cihazlar", path: "/pos-ayarlari/tanimli-cihazlar", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "terminals", title: "Terminaller", path: "/pos-ayarlari/terminaller", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "printers", title: "Yazicilar", path: "/pos-ayarlari/yazicilar", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "back-screen-slider", title: "Arka Ekran Slider", path: "/pos-ayarlari/arka-ekran-slider", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "table-colors", title: "Masa Renkleri", path: "/pos-ayarlari/masa-renkleri", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "discount-types", title: "Indirim Turleri", path: "/pos-ayarlari/indirim-turleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "preset-notes", title: "On Tanimli Notlar", path: "/pos-ayarlari/on-tanimli-notlar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "pos-settings", title: "Ayarlar", path: "/pos-ayarlari/ayarlar", listView: false, detailView: false, createFlow: false, exportable: false },
  { module: "staff", title: "Personel Yonetimi", path: "/personel", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-team", title: "Yonetici & Personel", path: "/personel/yonetici-ve-personel", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-goals", title: "Hedefler", path: "/personel/hedefler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-notifications", title: "Personel Bildirimleri", path: "/personel/personel-bildirimleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-shifts", title: "Mesai Yonetimi", path: "/personel/mesai-yonetimi", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-breaks", title: "Mola Sureleri", path: "/personel/mola-sureleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-tracking", title: "Personel Takip", path: "/personel/personel-takip", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "staff-roles", title: "Personel Rolleri", path: "/personel/personel-rolleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-tasks", title: "Gorevler", path: "/personel/gorev-ve-todo", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-audit-questions", title: "Operasyon Denetim Sorulari", path: "/personel/operasyon-devamli-sorular", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "staff-audit-survey", title: "Operasyon Denetim Anketi", path: "/personel/operasyon-devamli-anketi", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "attendance", title: "Mesai / Mola QR", path: "/mesai-qr", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "accounting", title: "Muhasebe Kayitlari", path: "/muhasebe", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "accounts", title: "Hesaplar", path: "/muhasebe/hesaplar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "ticket-ledger", title: "Adisyon Listesi", path: "/muhasebe/adisyon-listesi", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "sold-products", title: "Satilan Urunler", path: "/muhasebe/satilan-urunler", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "payments", title: "Odemeler", path: "/muhasebe/odemeler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "vat-rates", title: "Urun KDV Oranlari", path: "/muhasebe/urun-kdv-oranlari", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "suppliers", title: "Tedarikciler", path: "/muhasebe/tedarikciler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "supplier-vat", title: "Tedarikci KDV Raporlari", path: "/muhasebe/tedarikci-kdv-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "business-customers", title: "Musteri Isletmeler", path: "/muhasebe/musteri-isletmeler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "customer-vat", title: "Musteri KDV Raporlari", path: "/muhasebe/musteri-kdv-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "invoices", title: "Faturalar", path: "/muhasebe/faturalar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "invoice-items", title: "Fatura Kalemleri", path: "/muhasebe/fatura-kalemleri", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "unit-costs", title: "Birim Maliyetler", path: "/muhasebe/birim-maliyetler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "cash-closures", title: "Kasa Kapanislari", path: "/muhasebe/kasa-kapanislari", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "fixed-costs", title: "Sabit Maliyetler", path: "/muhasebe/sabit-maliyetler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "payroll", title: "Personel Odemeleri", path: "/muhasebe/personel-odemeleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "other-payments", title: "Diger Odemeler", path: "/muhasebe/diger-odemeler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "inventory", title: "Stok", path: "/stok", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "warehouses", title: "Depolar", path: "/stok/depolar", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "stock-transfer", title: "Depo Transfer", path: "/stok/depo-transfer", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "inventory-units", title: "Stok Birimleri", path: "/stok/stok-birimleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "inventory-categories", title: "Stoklu Urun Kategorileri", path: "/stok/stoklu-urun-kategorileri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "inventory-items", title: "Stoklu Urunler", path: "/stok/stoklu-urunler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "stock-entry", title: "Stok Girisi", path: "/stok/stok-girisi", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "stock-status", title: "Stok Durumu", path: "/stok/stok-durumu", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "stock-cards", title: "Stok Kartlari", path: "/stok/stok-kartlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "waste-products", title: "Atik Urunler", path: "/stok/atik-urunler", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "reports", title: "Raporlar", path: "/raporlar", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "sales-reports", title: "Satis Raporlari", path: "/raporlar/satis-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "payment-method-reports", title: "Odeme Tipi Raporlari", path: "/raporlar/odeme-tipi-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "expense-reports", title: "Gider Raporlari", path: "/raporlar/gider-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "cash-closure-reports", title: "Kasa Kapanis Raporlari", path: "/raporlar/kasa-kapanis-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "discount-reports", title: "Indirim Raporlari", path: "/raporlar/indirim-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "product-reports", title: "Urun Raporlari", path: "/raporlar/urun-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "profitability-reports", title: "Maliyet & Karlilik", path: "/raporlar/maliyet-karlilik-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "stock-reports", title: "Stok Raporlari", path: "/raporlar/stok-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "consumption-reports", title: "Hammadde Tuketim", path: "/raporlar/hammadde-tuketim-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "finance-reports", title: "Finans Raporlari", path: "/raporlar/finans-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "employee-reports", title: "Calisan Raporlari", path: "/raporlar/calisan-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "shift-reports", title: "Mesai Raporlari", path: "/raporlar/mesai-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "goal-bonus-reports", title: "Hedef & Prim Raporlari", path: "/raporlar/hedef-ve-prim-raporlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "integrations", title: "Entegrasyonlar", path: "/entegrasyonlar", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "pos-devices", title: "POS Cihazlari", path: "/entegrasyonlar/pos-cihazlari", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "subscription", title: "Abonelik", path: "/abonelik", listView: true, detailView: true, createFlow: true, exportable: false },
  { module: "product-ratings", title: "Urun Puanlari", path: "/urun-puanlari", listView: true, detailView: true, createFlow: false, exportable: true },
  { module: "staff-discounts", title: "Personel Indirimleri", path: "/personel/personel-indirimleri", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "support", title: "Destek", path: "/destek", listView: true, detailView: true, createFlow: true, exportable: true },
  { module: "go-pos", title: "Satis Ekranina Git", path: "/satis-ekranina-git", listView: false, detailView: false, createFlow: false, exportable: false },
];
