import { permissionCatalog } from "./permissions";

export const roleMatrix = {
  super_admin: Object.values(permissionCatalog).flat(),
  tenant_owner: [
    ...permissionCatalog.dashboard,
    ...permissionCatalog.ciro,
    ...permissionCatalog.menu,
    ...permissionCatalog.campaigns,
    ...permissionCatalog.tables,
    ...permissionCatalog.pos,
    ...permissionCatalog.pos_settings,
    ...permissionCatalog.customers,
    ...permissionCatalog.staff,
    ...permissionCatalog.attendance,
    ...permissionCatalog.inventory,
    ...permissionCatalog.accounting,
    ...permissionCatalog.reports,
    ...permissionCatalog.integrations,
    ...permissionCatalog.subscription,
    ...permissionCatalog.support,
    ...permissionCatalog.feature_flags,
    ...permissionCatalog.monitoring,
  ],
  branch_manager: [
    "dashboard.view",
    "ciro.view",
    "menu.view",
    "menu.manage",
    "campaign.view",
    "campaign.manage",
    "table.view",
    "table.manage",
    "ticket.view",
    "ticket.manage",
    "payment.manage",
    "pos_settings.view",
    "pos_settings.manage",
    "customer.view",
    "customer.manage",
    "staff.view",
    "staff.manage",
    "attendance.approve",
    "attendance.view",
    "attendance.manage",
    "inventory.view",
    "inventory.manage",
    "inventory.transfer",
    "inventory.export",
    "accounting.view",
    "accounting.manage",
    "accounting.export",
    "cash_closure.manage",
    "reports.view",
    "reports.export",
    "integrations.view",
    "integrations.manage",
    "subscription.view",
    "support.view",
    "support.manage",
    "monitoring.view",
  ],
  cashier: ["dashboard.view", "table.view", "ticket.view", "ticket.manage", "payment.manage", "customer.view", "attendance.view"],
  waiter: ["table.view", "ticket.view", "ticket.manage", "customer.view", "attendance.view"],
  kitchen: ["ticket.view"],
  accounting: ["accounting.view", "accounting.manage", "reports.view", "reports.export"],
  stock_manager: ["inventory.view", "inventory.manage", "inventory.transfer", "inventory.export", "reports.view", "reports.export"],
  hr: ["staff.view", "staff.manage", "attendance.view", "attendance.manage", "attendance.approve", "goal.manage"],
  auditor: ["reports.view", "reports.export", "dashboard.view", "ciro.view"],
} as const;

export type RoleKey = keyof typeof roleMatrix;
