export interface ApiEndpointDefinition {
  module: string;
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  scope: "public" | "tenant" | "branch" | "user";
}

export const apiCatalog: ApiEndpointDefinition[] = [
  { module: "auth", method: "POST", path: "/auth/login", summary: "Kullanici girisi", scope: "public" },
  { module: "auth", method: "POST", path: "/auth/refresh", summary: "Refresh token yenileme", scope: "public" },
  { module: "auth", method: "POST", path: "/auth/logout", summary: "Refresh session iptal et", scope: "user" },
  { module: "auth", method: "GET", path: "/auth/me", summary: "Aktif kullanici profili", scope: "user" },
  { module: "companies", method: "GET", path: "/companies", summary: "Sirketleri listele", scope: "tenant" },
  { module: "companies", method: "POST", path: "/companies", summary: "Sirket olustur", scope: "tenant" },
  { module: "branches", method: "GET", path: "/branches", summary: "Subeleri listele", scope: "tenant" },
  { module: "branches", method: "POST", path: "/branches", summary: "Sube olustur", scope: "tenant" },
  { module: "pos-settings", method: "GET", path: "/pos-settings/:resource/meta", summary: "POS ayari meta bilgisi", scope: "tenant" },
  { module: "pos-settings", method: "GET", path: "/pos-settings/:resource", summary: "POS ayari listele", scope: "tenant" },
  { module: "pos-settings", method: "POST", path: "/pos-settings/:resource", summary: "POS ayari olustur", scope: "tenant" },
  { module: "pos-settings", method: "PATCH", path: "/pos-settings/:resource/:id", summary: "POS ayari guncelle", scope: "tenant" },
  { module: "pos-settings", method: "DELETE", path: "/pos-settings/:resource/:id", summary: "POS ayari sil", scope: "tenant" },
  { module: "iam", method: "GET", path: "/iam/users", summary: "Kullanicilari listele", scope: "tenant" },
  { module: "iam", method: "POST", path: "/iam/users", summary: "Kullanici olustur", scope: "tenant" },
  { module: "iam", method: "GET", path: "/iam/roles", summary: "Rolleri listele", scope: "tenant" },
  { module: "iam", method: "GET", path: "/iam/permissions", summary: "Permission katalogu", scope: "tenant" },
  { module: "dashboard", method: "GET", path: "/dashboard/overview", summary: "Dashboard KPI ozeti", scope: "branch" },
  { module: "dashboard", method: "GET", path: "/dashboard/export", summary: "Dashboard widget export", scope: "branch" },
  { module: "menu", method: "GET", path: "/menu/categories", summary: "Kategori listesi", scope: "branch" },
  { module: "menu", method: "POST", path: "/menu/products", summary: "Urun olustur", scope: "branch" },
  { module: "campaigns", method: "GET", path: "/campaigns", summary: "Kampanya listesi", scope: "branch" },
  { module: "tables", method: "GET", path: "/tables/layout", summary: "Masa plani", scope: "branch" },
  { module: "pos", method: "GET", path: "/pos/tickets", summary: "Adisyon listesi", scope: "branch" },
  { module: "pos", method: "GET", path: "/pos/catalog", summary: "POS katalog verisi", scope: "branch" },
  { module: "pos", method: "GET", path: "/pos/tables", summary: "POS masa ve durum listesi", scope: "branch" },
  { module: "pos", method: "GET", path: "/pos/pending-orders", summary: "Bekleyen QR, paket ve gel-al siparisleri", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets", summary: "Adisyon olustur", scope: "branch" },
  { module: "pos", method: "PATCH", path: "/pos/tickets/:ticketId", summary: "Adisyon baslik bilgilerini guncelle", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/items", summary: "Adisyona urun ekle", scope: "branch" },
  { module: "pos", method: "PATCH", path: "/pos/tickets/:ticketId/items/:itemId", summary: "Adisyon satirini guncelle", scope: "branch" },
  { module: "pos", method: "DELETE", path: "/pos/tickets/:ticketId/items/:itemId", summary: "Adisyon satirini iptal et", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/notes", summary: "Adisyon veya satir notu ekle", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/discounts", summary: "Satir ya da adisyon indirimi uygula", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/payments", summary: "Odeme al", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/split", summary: "Adisyon bol", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/merge", summary: "Adisyon birlestir", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/transfer", summary: "Adisyonu baska masaya tasi", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/void", summary: "Adisyon iptal et", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/tickets/:ticketId/refund", summary: "Iade islemi baslat", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/approvals", summary: "Kritik POS islem onayi iste", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/printers/dispatch", summary: "Mutfak, fis veya etiket yazdir", scope: "branch" },
  { module: "pos", method: "POST", path: "/pos/drawer/open", summary: "Nakit cekmecesi ac", scope: "branch" },
  { module: "customers", method: "GET", path: "/customers", summary: "Musteri listesi", scope: "branch" },
  { module: "staff", method: "GET", path: "/staff/team", summary: "Personel modulu listesi", scope: "tenant" },
  { module: "staff", method: "GET", path: "/staff/:resource/meta", summary: "Personel modul metadata", scope: "tenant" },
  { module: "attendance", method: "GET", path: "/attendance/overview", summary: "Mesai QR panel ozet", scope: "branch" },
  { module: "attendance", method: "POST", path: "/attendance/qr/tokens", summary: "Mesai QR token olustur", scope: "branch" },
  { module: "attendance", method: "POST", path: "/attendance/qr/scan", summary: "QR ile mesai/mola islemi", scope: "public" },
  { module: "accounting", method: "GET", path: "/accounting/overview", summary: "Muhasebe ozet kartlari", scope: "tenant" },
  { module: "accounting", method: "GET", path: "/accounting/:resource/meta", summary: "Muhasebe modul metadata", scope: "tenant" },
  { module: "accounting", method: "GET", path: "/accounting/:resource", summary: "Muhasebe modul listesi", scope: "tenant" },
  { module: "accounting", method: "GET", path: "/accounting/:resource/export", summary: "Muhasebe CSV export", scope: "tenant" },
  { module: "inventory", method: "GET", path: "/inventory/overview", summary: "Stok ozet kartlari", scope: "tenant" },
  { module: "inventory", method: "POST", path: "/inventory/sync-sales", summary: "Satislardan stok dusum senkronu", scope: "tenant" },
  { module: "inventory", method: "GET", path: "/inventory/:resource/meta", summary: "Stok modul metadata", scope: "tenant" },
  { module: "inventory", method: "GET", path: "/inventory/:resource", summary: "Stok modul listesi", scope: "tenant" },
  { module: "inventory", method: "GET", path: "/inventory/:resource/export", summary: "Stok CSV export", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/catalog", summary: "Rapor katalog listesi", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/:report", summary: "Dinamik rapor verisi", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/:report/export", summary: "Dinamik rapor export", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/revenue/overview", summary: "Ciro genel bakis raporu", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/revenue/branches", summary: "Sube bazli ciro raporu", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/revenue/export", summary: "Ciro export", scope: "tenant" },
  { module: "reports", method: "GET", path: "/reports/revenue/branches/export", summary: "Sube bazli ciro export", scope: "tenant" },
  { module: "integrations", method: "GET", path: "/integrations/overview", summary: "Entegrasyon ozet kartlari", scope: "tenant" },
  { module: "integrations", method: "GET", path: "/integrations/providers", summary: "Entegrasyon saglayicilari", scope: "tenant" },
  { module: "integrations", method: "GET", path: "/integrations/credentials", summary: "Bagli entegrasyon credential listesi", scope: "tenant" },
  { module: "integrations", method: "POST", path: "/integrations/credentials", summary: "Entegrasyon credential olustur", scope: "tenant" },
  { module: "integrations", method: "PATCH", path: "/integrations/credentials/:id", summary: "Entegrasyon credential guncelle", scope: "tenant" },
  { module: "integrations", method: "DELETE", path: "/integrations/credentials/:id", summary: "Entegrasyon credential sil", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/overview", summary: "Aktif abonelik ve limit ozeti", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/plans", summary: "Abonelik plan listesi", scope: "tenant" },
  { module: "subscriptions", method: "POST", path: "/subscriptions/change-plan", summary: "Abonelik plani degistir", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/platform-meta", summary: "Platform modulleri form metadata", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/product-ratings", summary: "Urun puanlari listesi", scope: "tenant" },
  { module: "subscriptions", method: "POST", path: "/subscriptions/product-ratings", summary: "Urun puani olustur", scope: "tenant" },
  { module: "subscriptions", method: "PATCH", path: "/subscriptions/product-ratings/:id", summary: "Urun puani guncelle", scope: "tenant" },
  { module: "subscriptions", method: "DELETE", path: "/subscriptions/product-ratings/:id", summary: "Urun puani sil", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/staff-discounts", summary: "Personel indirimleri listesi", scope: "tenant" },
  { module: "subscriptions", method: "POST", path: "/subscriptions/staff-discounts", summary: "Personel indirimi olustur", scope: "tenant" },
  { module: "subscriptions", method: "PATCH", path: "/subscriptions/staff-discounts/:id", summary: "Personel indirimi guncelle", scope: "tenant" },
  { module: "subscriptions", method: "DELETE", path: "/subscriptions/staff-discounts/:id", summary: "Personel indirimi sil", scope: "tenant" },
  { module: "subscriptions", method: "GET", path: "/subscriptions/go-pos-link", summary: "Satis ekranina gecis linki", scope: "tenant" },
  { module: "support", method: "GET", path: "/support/meta", summary: "Destek metadata", scope: "tenant" },
  { module: "support", method: "GET", path: "/support/tickets", summary: "Destek talep listesi", scope: "tenant" },
  { module: "support", method: "POST", path: "/support/tickets", summary: "Destek talebi olustur", scope: "tenant" },
  { module: "support", method: "PATCH", path: "/support/tickets/:id", summary: "Destek talebi guncelle", scope: "tenant" },
  { module: "support", method: "DELETE", path: "/support/tickets/:id", summary: "Destek talebi sil", scope: "tenant" },
  { module: "audit", method: "GET", path: "/audit/logs", summary: "Audit log listesi", scope: "tenant" },
  { module: "notifications", method: "GET", path: "/notifications", summary: "Bildirim listesi", scope: "user" },
  { module: "notifications", method: "PATCH", path: "/notifications/:id/read", summary: "Bildirim okundu yap", scope: "user" },
  { module: "notifications", method: "POST", path: "/notifications/read-all", summary: "Tum bildirimleri okundu yap", scope: "user" },
  { module: "notifications", method: "POST", path: "/notifications/push-token", summary: "Expo push token kaydet", scope: "user" },
];
