import type { StaffResource } from "./staff.resources";

export interface StaffFieldOption {
  label: string;
  value: string;
}

export interface StaffFieldConfig {
  key: string;
  label: string;
  type: "text" | "number" | "textarea" | "switch" | "select" | "datetime" | "json";
  required?: boolean;
  options?: StaffFieldOption[];
}

export interface StaffColumnConfig {
  key: string;
  label: string;
}

export interface StaffFilterConfig {
  key: string;
  label: string;
  type: "text" | "select" | "boolean" | "date";
  options?: StaffFieldOption[];
}

export interface StaffResourceConfig {
  key: StaffResource;
  title: string;
  description: string;
  delegate: string;
  branchScoped: boolean;
  include?: Record<string, unknown>;
  searchFields: string[];
  orderBy: Record<string, "asc" | "desc">;
  fields: StaffFieldConfig[];
  columns: StaffColumnConfig[];
  filters: StaffFilterConfig[];
  numberFields?: string[];
  booleanFields?: string[];
  jsonFields?: string[];
  dateFields?: string[];
  relationOptionKeys?: Array<"branches" | "users" | "employees" | "permissions" | "roles" | "staffRoles" | "products" | "categories">;
}

export const staffRegistry: Record<StaffResource, StaffResourceConfig> = {
  team: {
    key: "team",
    title: "Yonetici & Personel",
    description: "Kullanici, profil ve rol atama yonetimi",
    delegate: "employeeProfile",
    branchScoped: true,
    include: {
      branch: true,
      company: true,
      staffRole: true,
      user: { include: { roles: { include: { role: true, branch: true } } } },
      personalProfile: true,
      contactProfile: true,
      financialProfile: true,
      emergencyContact: true,
      statusLogs: { orderBy: { createdAt: "desc" }, take: 10 },
    },
    searchFields: ["employeeCode", "department", "title"],
    orderBy: { employeeCode: "asc" },
    relationOptionKeys: ["branches", "roles", "staffRoles"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "firstName", label: "Ad", type: "text", required: true },
      { key: "lastName", label: "Soyad", type: "text" },
      { key: "employeeCode", label: "Personel Kodu", type: "text", required: true },
      { key: "fullName", label: "Ad Soyad", type: "text", required: true },
      { key: "email", label: "E-posta", type: "text" },
      { key: "phone", label: "Telefon", type: "text" },
      { key: "password", label: "Sifre", type: "text" },
      { key: "pinCode", label: "PIN Kodu", type: "text" },
      { key: "department", label: "Departman", type: "text" },
      { key: "title", label: "Unvan", type: "text" },
      { key: "restaurantRole", label: "Restoran Rolu", type: "text" },
      { key: "staffRoleId", label: "Personel Rol Kaydi", type: "select" },
      { key: "lateToleranceMinutes", label: "Gec Kalma Toleransi (dk)", type: "number" },
      { key: "hireDate", label: "Ise Giris", type: "datetime" },
      { key: "birthDate", label: "Dogum Tarihi", type: "datetime" },
      { key: "salary", label: "Maas", type: "number" },
      { key: "isActive", label: "Aktif", type: "switch" },
      { key: "isOwner", label: "Isletme Sahibi", type: "switch" },
      { key: "overtimeEnabled", label: "Mesai Aktif", type: "switch" },
      { key: "dailyFreeDrinkLimit", label: "Gunluk Ucretsiz Icecek", type: "number" },
      { key: "totalBreakMinutes", label: "Toplam Mola Suresi (dk)", type: "number" },
      { key: "photo", label: "Profil Fotografı", type: "text" },
      { key: "nationality", label: "Uyruk", type: "text" },
      { key: "identityNumber", label: "Kimlik Numarasi", type: "text" },
      { key: "gender", label: "Cinsiyet", type: "text" },
      { key: "bloodType", label: "Kan Grubu", type: "text" },
      { key: "disabilityStatus", label: "Engel Durumu", type: "text" },
      { key: "educationStatus", label: "Egitim Durumu", type: "text" },
      { key: "highestEducationLevel", label: "Tamamlanan En Yuksek Egitim", type: "text" },
      { key: "lastEducationSchool", label: "Son Tamamlanan Egitim Kurumu", type: "text" },
      { key: "maritalStatus", label: "Medeni Durum", type: "text" },
      { key: "childrenCount", label: "Cocuk Sayisi", type: "number" },
      { key: "address", label: "Adres", type: "textarea" },
      { key: "country", label: "Ulke", type: "text" },
      { key: "city", label: "Sehir", type: "text" },
      { key: "district", label: "Ilce", type: "text" },
      { key: "postalCode", label: "Posta Kodu", type: "text" },
      { key: "homePhone", label: "Ev Telefonu", type: "text" },
      { key: "salaryPaymentDay", label: "Maas Odeme Gunu", type: "number" },
      { key: "bankName", label: "Banka Adi", type: "text" },
      { key: "accountType", label: "Hesap Turu", type: "text" },
      { key: "accountNumber", label: "Hesap Numarasi", type: "text" },
      { key: "iban", label: "IBAN", type: "text" },
      { key: "contactName", label: "Acil Durum Kisi", type: "text" },
      { key: "contactPhone", label: "Acil Durum Telefon", type: "text" },
      { key: "relation", label: "Yakinlik", type: "text" },
      { key: "roleKeysJson", label: "Rol Anahtarlari JSON", type: "json" },
    ],
    columns: [
      { key: "employeeCode", label: "Kod" },
      { key: "user.fullName", label: "Ad Soyad" },
      { key: "department", label: "Departman" },
      { key: "title", label: "Unvan" },
      { key: "lateToleranceMinutes", label: "Tolerans" },
      { key: "branch.name", label: "Sube" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["salary", "lateToleranceMinutes", "dailyFreeDrinkLimit", "totalBreakMinutes", "childrenCount", "salaryPaymentDay"],
    booleanFields: ["isActive", "isOwner", "overtimeEnabled"],
    jsonFields: ["roleKeysJson"],
    dateFields: ["hireDate", "birthDate"],
  },
  payroll: {
    key: "payroll",
    title: "Maas Yonetimi",
    description: "Personel maas odeme kayitlari",
    delegate: "payrollPayment",
    branchScoped: true,
    include: { branch: true, employeeProfile: { include: { user: true } } },
    searchFields: ["notes"],
    orderBy: { paymentDate: "desc" },
    relationOptionKeys: ["branches", "employees"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "employeeProfileId", label: "Personel", type: "select", required: true },
      { key: "amount", label: "Tutar", type: "number", required: true },
      { key: "paymentDate", label: "Odeme Tarihi", type: "datetime", required: true },
      { key: "notes", label: "Not", type: "textarea" },
    ],
    columns: [
      { key: "employeeProfile.user.fullName", label: "Personel" },
      { key: "branch.name", label: "Sube" },
      { key: "amount", label: "Tutar" },
      { key: "paymentDate", label: "Odeme Tarihi" },
      { key: "notes", label: "Not" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["amount"],
    dateFields: ["paymentDate"],
  },
  "staff-discounts": {
    key: "staff-discounts",
    title: "Personel Indirimleri",
    description: "Personel bazli indirim kurallari",
    delegate: "staffDiscount",
    branchScoped: true,
    include: { branch: true, employeeProfile: { include: { user: true } } },
    searchFields: ["title", "discountType"],
    orderBy: { createdAt: "desc" },
    relationOptionKeys: ["branches", "employees"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "employeeProfileId", label: "Personel", type: "select", required: true },
      { key: "title", label: "Indirim Basligi", type: "text", required: true },
      {
        key: "discountType",
        label: "Indirim Tipi",
        type: "select",
        required: true,
        options: [
          { label: "Yuzde", value: "percentage" },
          { label: "Tutar", value: "amount" },
        ],
      },
      { key: "value", label: "Deger", type: "number", required: true },
      { key: "dailyLimit", label: "Gunluk Limit", type: "number" },
      { key: "monthlyLimit", label: "Aylik Limit", type: "number" },
      { key: "approvalRequired", label: "Onay Gerekli", type: "switch" },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "title", label: "Indirim Basligi" },
      { key: "employeeProfile.user.fullName", label: "Personel" },
      { key: "branch.name", label: "Sube" },
      { key: "discountType", label: "Tip" },
      { key: "value", label: "Deger" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["value", "dailyLimit", "monthlyLimit"],
    booleanFields: ["approvalRequired", "isActive"],
  },
  goals: {
    key: "goals",
    title: "Hedefler",
    description: "Satis hedefi, ilerleme ve prim kurgusu",
    delegate: "goal",
    branchScoped: true,
    include: {
      branch: true,
      employeeProfile: { include: { user: true, branch: true } },
      product: true,
      category: true,
      bonus: true,
    },
    searchFields: ["title", "description", "goalType", "goalScope", "status"],
    orderBy: { startsAt: "desc" },
    relationOptionKeys: ["branches", "employees", "products", "categories"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "employeeProfileId", label: "Personel", type: "select" },
      { key: "title", label: "Hedef", type: "text", required: true },
      { key: "description", label: "Aciklama", type: "textarea" },
      { key: "goalScope", label: "Hedef Kapsami", type: "select", required: true, options: [
        { label: "Genel Isletme", value: "general" },
        { label: "Personel Bazli", value: "employee" },
      ] },
      { key: "goalType", label: "Hedef Tipi", type: "select", required: true, options: [
        { label: "Urun Satis Adedi", value: "product_quantity" },
        { label: "Kategori Satis Adedi", value: "category_quantity" },
        { label: "Ciro Hedefi", value: "revenue" },
        { label: "Odeme Tipi Hedefi", value: "payment_method_total" },
      ] },
      { key: "productId", label: "Urun", type: "select" },
      { key: "categoryId", label: "Kategori", type: "select" },
      { key: "paymentMethod", label: "Odeme Tipi", type: "select", options: [
        { label: "Nakit", value: "CASH" },
        { label: "Kredi Karti", value: "CREDIT_CARD" },
        { label: "Yemek Karti", value: "MEAL_CARD" },
        { label: "Hediye Ceki / Kart", value: "GIFT_CARD" },
        { label: "Havale / EFT", value: "BANK_TRANSFER" },
        { label: "Diger", value: "OTHER" },
      ] },
      { key: "targetValue", label: "Hedef Deger", type: "number", required: true },
      { key: "bonusType", label: "Prim Tipi", type: "select", options: [
        { label: "Sabit Tutar", value: "fixed" },
        { label: "Yuzde", value: "percentage" },
      ] },
      { key: "bonusValue", label: "Prim Degeri", type: "number" },
      { key: "bonusApprovalRequired", label: "Prim Onayi Gerekli", type: "switch" },
      { key: "manualOverrideValue", label: "Manuel Override Degeri", type: "number" },
      { key: "manualOverrideNote", label: "Override Notu", type: "textarea" },
      { key: "startsAt", label: "Baslangic", type: "datetime", required: true },
      { key: "endsAt", label: "Bitis", type: "datetime", required: true },
    ],
    columns: [
      { key: "title", label: "Hedef" },
      { key: "branch.name", label: "Sube" },
      { key: "goalTypeLabel", label: "Tip" },
      { key: "goalScopeLabel", label: "Kapsam" },
      { key: "ownerLabel", label: "Sorumlu" },
      { key: "targetValue", label: "Hedef" },
      { key: "currentValue", label: "Mevcut" },
      { key: "progressRateLabel", label: "Tamamlanma" },
      { key: "statusLabel", label: "Durum" },
      { key: "bonusSummaryLabel", label: "Prim" },
      { key: "endsAt", label: "Bitis" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
      { key: "status", label: "Durum", type: "select", options: [
        { label: "Aktif", value: "active" },
        { label: "Tamamlandi", value: "completed" },
        { label: "Suresi Doldu", value: "expired" },
      ] },
    ],
    numberFields: ["targetValue", "bonusValue", "manualOverrideValue"],
    booleanFields: ["bonusApprovalRequired"],
    dateFields: ["startsAt", "endsAt", "completedAt", "lastSyncedAt"],
  },
  notifications: {
    key: "notifications",
    title: "Personel Bildirimleri",
    description: "Personel bildirim ve duyuru akisi",
    delegate: "notification",
    branchScoped: true,
    include: { branch: true, user: true },
    searchFields: ["title", "message"],
    orderBy: { createdAt: "desc" },
    relationOptionKeys: ["branches", "users"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "userId", label: "Kullanici", type: "select" },
      { key: "type", label: "Tip", type: "select", options: [
        { label: "STOCK_ALERT", value: "STOCK_ALERT" },
        { label: "CASH_CLOSURE", value: "CASH_CLOSURE" },
        { label: "ATTENDANCE", value: "ATTENDANCE" },
        { label: "APPROVAL", value: "APPROVAL" },
        { label: "TASK", value: "TASK" },
        { label: "SYSTEM", value: "SYSTEM" },
      ], required: true },
      { key: "title", label: "Baslik", type: "text", required: true },
      { key: "message", label: "Mesaj", type: "textarea", required: true },
      { key: "data", label: "Data JSON", type: "json" },
      { key: "isRead", label: "Okundu", type: "switch" },
    ],
    columns: [
      { key: "title", label: "Bildirim" },
      { key: "recipientName", label: "Hedef" },
      { key: "branch.name", label: "Sube" },
      { key: "typeLabel", label: "Tip" },
      { key: "createdAt", label: "Tarih" },
      { key: "readStatusLabel", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
      { key: "userId", label: "Kullanici", type: "select" },
      { key: "type", label: "Tip", type: "select", options: [
        { label: "Gorev", value: "TASK" },
        { label: "Sistem", value: "SYSTEM" },
        { label: "Mesai", value: "ATTENDANCE" },
        { label: "Onay", value: "APPROVAL" },
        { label: "Stok", value: "STOCK_ALERT" },
        { label: "Kasa", value: "CASH_CLOSURE" },
      ] },
      { key: "isRead", label: "Okunma", type: "select", options: [
        { label: "Okunmadi", value: "false" },
        { label: "Okundu", value: "true" },
      ] },
    ],
    booleanFields: ["isRead"],
    jsonFields: ["data"],
    dateFields: ["createdAt"],
  },
  shifts: {
    key: "shifts",
    title: "Mesai Yonetimi",
    description: "Vardiya planlama ve onay durumu",
    delegate: "shift",
    branchScoped: true,
    include: { branch: true, employeeProfile: { include: { user: true } } },
    searchFields: ["approvalStatus", "notes"],
    orderBy: { scheduledStartAt: "desc" },
    relationOptionKeys: ["branches", "employees"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "employeeProfileId", label: "Personel", type: "select", required: true },
      { key: "scheduledStartAt", label: "Planli Baslangic", type: "datetime", required: true },
      { key: "scheduledEndAt", label: "Planli Bitis", type: "datetime", required: true },
      { key: "actualStartAt", label: "Gercek Baslangic", type: "datetime" },
      { key: "actualEndAt", label: "Gercek Bitis", type: "datetime" },
      { key: "totalBreakMinutes", label: "Toplam Mola", type: "number" },
      { key: "lateMinutes", label: "Gec Kalma", type: "number" },
      { key: "overtimeMinutes", label: "Fazla Mesai", type: "number" },
      { key: "approvalStatus", label: "Onay Durumu", type: "select", options: [
        { label: "approved", value: "approved" },
        { label: "pending", value: "pending" },
        { label: "rejected", value: "rejected" },
      ] },
      { key: "notes", label: "Not", type: "textarea" },
    ],
    columns: [
      { key: "employeeProfile.user.fullName", label: "Personel" },
      { key: "branch.name", label: "Sube" },
      { key: "scheduledStartAt", label: "Baslangic" },
      { key: "scheduledEndAt", label: "Bitis" },
      { key: "approvalStatus", label: "Onay" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["totalBreakMinutes", "lateMinutes", "overtimeMinutes"],
    dateFields: ["scheduledStartAt", "scheduledEndAt", "actualStartAt", "actualEndAt"],
  },
  breaks: {
    key: "breaks",
    title: "Mola Sureleri",
    description: "Baslat-bitir mola kayitlari",
    delegate: "breakRecord",
    branchScoped: false,
    include: { shift: { include: { branch: true } }, employeeProfile: { include: { user: true } } },
    searchFields: ["approvalStatus", "notes"],
    orderBy: { startedAt: "desc" },
    relationOptionKeys: ["employees"],
    fields: [
      { key: "employeeProfileId", label: "Personel", type: "select", required: true },
      { key: "shiftId", label: "Mesai ID", type: "text" },
      { key: "startedAt", label: "Mola Baslangic", type: "datetime", required: true },
      { key: "endedAt", label: "Mola Bitis", type: "datetime" },
      { key: "totalMinutes", label: "Sure", type: "number" },
      { key: "approvalStatus", label: "Onay Durumu", type: "select", options: [
        { label: "approved", value: "approved" },
        { label: "pending", value: "pending" },
        { label: "rejected", value: "rejected" },
      ] },
      { key: "notes", label: "Not", type: "textarea" },
    ],
    columns: [
      { key: "employeeProfile.user.fullName", label: "Personel" },
      { key: "startedAt", label: "Baslangic" },
      { key: "endedAt", label: "Bitis" },
      { key: "totalMinutes", label: "Sure" },
      { key: "approvalStatus", label: "Onay" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    numberFields: ["totalMinutes"],
    dateFields: ["startedAt", "endedAt"],
  },
  tracking: {
    key: "tracking",
    title: "Personel Takip",
    description: "Mesai hareket ve ihlal listesi",
    delegate: "attendanceEvent",
    branchScoped: true,
    include: { branch: true, employeeProfile: { include: { user: true } }, shift: true },
    searchFields: ["source", "approvalStatus", "note"],
    orderBy: { occurredAt: "desc" },
    relationOptionKeys: ["branches", "employees"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "employeeProfileId", label: "Personel", type: "select", required: true },
      { key: "action", label: "Aksiyon", type: "select", options: [
        { label: "SHIFT_IN", value: "SHIFT_IN" },
        { label: "SHIFT_OUT", value: "SHIFT_OUT" },
        { label: "BREAK_START", value: "BREAK_START" },
        { label: "BREAK_END", value: "BREAK_END" },
      ], required: true },
      { key: "occurredAt", label: "Zaman", type: "datetime", required: true },
      { key: "source", label: "Kaynak", type: "text" },
      { key: "lateMinutes", label: "Gec Kalma", type: "number" },
      { key: "overtimeMinutes", label: "Fazla Mesai", type: "number" },
      { key: "approvalStatus", label: "Onay", type: "select", options: [
        { label: "approved", value: "approved" },
        { label: "pending", value: "pending" },
        { label: "rejected", value: "rejected" },
      ] },
      { key: "note", label: "Not", type: "textarea" },
    ],
    columns: [
      { key: "employeeProfile.user.fullName", label: "Personel" },
      { key: "branch.name", label: "Sube" },
      { key: "action", label: "Aksiyon" },
      { key: "occurredAt", label: "Zaman" },
      { key: "approvalStatus", label: "Onay" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["lateMinutes", "overtimeMinutes"],
    dateFields: ["occurredAt"],
  },
  roles: {
    key: "roles",
    title: "Personel Rolleri",
    description: "Rol ve permission setleri",
    delegate: "role",
    branchScoped: false,
    include: { permissions: { include: { permission: true } } },
    searchFields: ["name", "key", "description"],
    orderBy: { name: "asc" },
    relationOptionKeys: ["permissions"],
    fields: [
      { key: "key", label: "Rol Key", type: "text", required: true },
      { key: "name", label: "Rol Adi", type: "text", required: true },
      { key: "description", label: "Aciklama", type: "textarea" },
      { key: "isSystem", label: "Sistem Rolu", type: "switch" },
      { key: "permissionKeysJson", label: "Permission JSON", type: "json", required: true },
    ],
    columns: [
      { key: "name", label: "Rol" },
      { key: "key", label: "Key" },
      { key: "isSystem", label: "Sistem" },
    ],
    filters: [{ key: "search", label: "Ara", type: "text" }],
    booleanFields: ["isSystem"],
    jsonFields: ["permissionKeysJson"],
  },
  tasks: {
    key: "tasks",
    title: "Gorevler",
    description: "Personel gorev yonetimi",
    delegate: "task",
    branchScoped: true,
    include: { branch: true, user: true, createdByUser: true },
    searchFields: ["title", "description", "status", "priority"],
    orderBy: { dueAt: "asc" },
    relationOptionKeys: ["branches", "users"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "userId", label: "Kullanici", type: "select", required: true },
      { key: "title", label: "Baslik", type: "text", required: true },
      { key: "description", label: "Aciklama", type: "textarea" },
      { key: "dueAt", label: "Termin", type: "datetime" },
      { key: "priority", label: "Oncelik", type: "select", options: [
        { label: "Dusuk", value: "low" },
        { label: "Orta", value: "medium" },
        { label: "Yuksek", value: "high" },
        { label: "Kritik", value: "critical" },
      ] },
      { key: "status", label: "Durum", type: "select", options: [
        { label: "Bekliyor", value: "todo" },
        { label: "Yapiliyor", value: "in_progress" },
        { label: "Tamamlandi", value: "done" },
      ] },
    ],
    columns: [
      { key: "title", label: "Gorev" },
      { key: "user.fullName", label: "Personel" },
      { key: "branch.name", label: "Sube" },
      { key: "dueAt", label: "Termin" },
      { key: "priorityLabel", label: "Oncelik" },
      { key: "statusLabel", label: "Durum" },
      { key: "createdByName", label: "Atayan" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
      { key: "userId", label: "Personel", type: "select" },
      { key: "priority", label: "Oncelik", type: "select", options: [
        { label: "Kritik", value: "critical" },
        { label: "Yuksek", value: "high" },
        { label: "Orta", value: "medium" },
        { label: "Dusuk", value: "low" },
      ] },
      { key: "status", label: "Durum", type: "select", options: [
        { label: "Bekliyor", value: "todo" },
        { label: "Yapiliyor", value: "in_progress" },
        { label: "Tamamlandi", value: "done" },
        { label: "Gecikti", value: "overdue" },
      ] },
      { key: "dateFrom", label: "Baslangic Tarihi", type: "date" },
      { key: "dateTo", label: "Bitis Tarihi", type: "date" },
    ],
    dateFields: ["dueAt"],
  },
  "audit-questions": {
    key: "audit-questions",
    title: "Operasyon Devamli Sorular",
    description: "Operasyon soru bankasi",
    delegate: "operationalAuditQuestion",
    branchScoped: true,
    include: { branch: true },
    searchFields: ["question", "category"],
    orderBy: { sortOrder: "asc" },
    relationOptionKeys: ["branches"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "question", label: "Soru", type: "textarea", required: true },
      { key: "category", label: "Kategori", type: "text" },
      { key: "weight", label: "Agirlik", type: "number" },
      { key: "sortOrder", label: "Sira", type: "number" },
      { key: "isActive", label: "Aktif", type: "switch" },
    ],
    columns: [
      { key: "question", label: "Soru" },
      { key: "category", label: "Kategori" },
      { key: "branch.name", label: "Sube" },
      { key: "weight", label: "Agirlik" },
      { key: "isActive", label: "Durum" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["weight", "sortOrder"],
    booleanFields: ["isActive"],
  },
  "audit-survey": {
    key: "audit-survey",
    title: "Operasyon Devamli Anketi",
    description: "Anket / denetim formu kayitlari",
    delegate: "operationalAuditSurvey",
    branchScoped: true,
    include: { branch: true, assignedToUser: true },
    searchFields: ["title", "description", "status"],
    orderBy: { createdAt: "desc" },
    relationOptionKeys: ["branches", "users"],
    fields: [
      { key: "branchId", label: "Sube", type: "select", required: true },
      { key: "assignedToUserId", label: "Atanan Kullanici", type: "select" },
      { key: "title", label: "Anket", type: "text", required: true },
      { key: "description", label: "Aciklama", type: "textarea" },
      { key: "status", label: "Durum", type: "select", options: [
        { label: "draft", value: "draft" },
        { label: "pending", value: "pending" },
        { label: "submitted", value: "submitted" },
        { label: "approved", value: "approved" },
      ] },
      { key: "dueAt", label: "Son Tarih", type: "datetime" },
      { key: "submittedAt", label: "Gonderim", type: "datetime" },
      { key: "score", label: "Skor", type: "number" },
      { key: "answersJson", label: "Cevaplar JSON", type: "json" },
    ],
    columns: [
      { key: "title", label: "Anket" },
      { key: "branch.name", label: "Sube" },
      { key: "assignedToUser.fullName", label: "Atanan" },
      { key: "status", label: "Durum" },
      { key: "score", label: "Skor" },
    ],
    filters: [
      { key: "search", label: "Ara", type: "text" },
      { key: "branchId", label: "Sube", type: "select" },
    ],
    numberFields: ["score"],
    jsonFields: ["answersJson"],
    dateFields: ["dueAt", "submittedAt"],
  },
};
